GR-77: Action registry
ggQuest/api-v2-nest pull request #155
Opened 2023-08-31 12:19 UTC by vladikopl01

Jira: https://ggquestdev.atlassian.net/browse/GR-77

2023-08-31 12:43 UTC, yura2100 requested changes
@vladikopl01 what about swagger docs?

Please add prisma migrations once https://github.com/ggQuest/api-v2-nest/pull/154 is landed

2023-08-31 12:43 UTC, yura2100 commented on abi/ActionDispatcher.json
I am not sure if we need this

2023-08-31 12:43 UTC, yura2100 commented on docker-compose.yml
Please don't include it in the PR

2023-08-31 12:43 UTC, yura2100 commented on package-lock.json
Once you install dependencies locally use `npm ci`. This way `package-lock.json` won't be affected.
Could you please rollback it?

2023-08-31 12:43 UTC, yura2100 commented on prisma/schema.prisma
> +  id        String   @id @default(uuid())
Unfortunately numeric ids are used through all other tables.
Please use `id      Int    @id @default(autoincrement())`

2023-08-31 12:43 UTC, yura2100 commented on prisma/schema.prisma
> +  gameId    String   @map("game_id")
Please add a relation to game as well

2023-08-31 12:43 UTC, yura2100 commented on prisma/schema.prisma
> +  hash      String
Hash must be unique

2023-08-31 12:43 UTC, yura2100 commented on src/action-registry/action-registry.controller.spec.ts
> +  beforeEach(async () => {
I believe this test would fail as you don't provide a service to IoC container

2023-08-31 12:43 UTC, yura2100 commented on src/action-registry/action-registry.controller.ts
> +@Controller('action-registry')
Let's use just `actions` resource name
```suggestion
@Controller('actions')
```

2023-08-31 12:43 UTC, yura2100 commented on src/action-registry/action-registry.controller.ts
> +  async getOneByActionId(@Param('actionId') actionId: string) {
```suggestion
  @Get(':hash')
  async getOneByActionId(@Param('hash') hash: string) {
```

2023-08-31 12:43 UTC, yura2100 commented on src/action-registry/action-registry.controller.ts
> +  async createAction(@Body() dto: CreateActionDto) {
There is no sense to add `Action` suffix as we already in `ActionRegistryController`
```suggestion
  async create(@Body() dto: CreateActionDto) {
```

2023-08-31 12:43 UTC, yura2100 commented on src/action-registry/action-registry.controller.ts
> +    @Param('actionId') actionId: string,
```suggestion
  @Patch(':hash')
  async update(
    @Param('hash') hash: string,
```

2023-08-31 12:43 UTC, yura2100 commented on src/action-registry/action-registry.service.spec.ts
> +  beforeEach(async () => {
I guess this test will fail as well

2023-08-31 12:43 UTC, yura2100 commented on src/action-registry/action-registry.service.ts
> +  isAllowed(gameId: string, actions: string[]): Promise<boolean> {
?

2023-08-31 12:43 UTC, yura2100 commented on src/action-registry/types.ts
This is pretty generic. Maybe we could move it somewhere else. 

@vladikopl01 Does actions CRUD follows this response shape or we have a generic interceptor for this?

2023-08-31 12:43 UTC, yura2100 commented on src/action-registry/action-registry.service.ts
> +  async createAction(dto: CreateActionDto) {
```suggestion
  async create(dto: CreateActionDto) {
```

2023-08-31 12:43 UTC, yura2100 commented on src/action-registry/action-registry.service.ts
> +  async updateAction(actionId: string, dto: UpdateActionDto) {
```suggestion
  async update(actionId: string, dto: UpdateActionDto) {
```

2023-08-31 12:43 UTC, yura2100 commented on src/action-registry/dto/update-action.dto.ts
> +}
Please map existing types instead of duplicating
```suggestion
import { PickType } from '@nestjs/swagger';
import { CreateActionDto } from './create-action.dto';

export class UpdateActionDto extends PickType(CreateActionDto, ['action'] as const) {}
```

2023-08-31 13:01 UTC, vladikopl01 commented on abi/ActionDispatcher.json
Solved in https://github.com/ggQuest/api-v2-nest/pull/155/commits/bd4a287b35da3835d352f89d08796ed77b441e06

2023-08-31 13:02 UTC, vladikopl01 commented on src/action-registry/action-registry.controller.ts
> +  async createAction(@Body() dto: CreateActionDto) {
Solved in https://github.com/ggQuest/api-v2-nest/pull/155/commits/bd4a287b35da3835d352f89d08796ed77b441e06

2023-08-31 13:03 UTC, vladikopl01 commented on src/action-registry/action-registry.service.ts
> +  async createAction(dto: CreateActionDto) {
Solved in https://github.com/ggQuest/api-v2-nest/pull/155/commits/bd4a287b35da3835d352f89d08796ed77b441e06

2023-08-31 13:03 UTC, vladikopl01 commented on src/action-registry/action-registry.service.ts
> +  async updateAction(actionId: string, dto: UpdateActionDto) {
Solved in https://github.com/ggQuest/api-v2-nest/pull/155/commits/bd4a287b35da3835d352f89d08796ed77b441e06

2023-08-31 13:07 UTC, vladikopl01 commented on package-lock.json
I tried to use the old one `package-lock.json` file and run `npm ci` but got an error about unsynced `package.json` and `package-lock.json` files

```
`npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
```

2023-08-31 13:15 UTC, vladikopl01 commented on prisma/schema.prisma
> +  gameId    String   @map("game_id")
@yura2100 What do you mean by relation?

2023-08-31 15:42 UTC, vladikopl01 commented on package-lock.json
As we discussed today, I will change the CI workflow not to run `npm install`

2023-08-31 17:53 UTC, vladikopl01 commented on prisma/schema.prisma
> +  id        String   @id @default(uuid())
Solved in https://github.com/ggQuest/api-v2-nest/pull/155/commits/f0ea79383f084b19ebde6857e81bdbb68968bf61

2023-08-31 17:54 UTC, vladikopl01 commented on prisma/schema.prisma
> +  hash      String
Solved in https://github.com/ggQuest/api-v2-nest/pull/155/commits/f0ea79383f084b19ebde6857e81bdbb68968bf61

2023-08-31 17:54 UTC, vladikopl01 commented on src/action-registry/action-registry.controller.ts
> +    @Param('actionId') actionId: string,
Solved in https://github.com/ggQuest/api-v2-nest/pull/155/commits/95f3a4946b4168316ed5336c418ae51631183201

2023-08-31 17:54 UTC, vladikopl01 commented on src/action-registry/action-registry.controller.ts
> +  async createAction(@Body() dto: CreateActionDto) {
Solved in https://github.com/ggQuest/api-v2-nest/pull/155/commits/95f3a4946b4168316ed5336c418ae51631183201

2023-08-31 17:55 UTC, vladikopl01 commented on src/action-registry/action-registry.controller.ts
> +  async getOneByActionId(@Param('actionId') actionId: string) {
Solved in https://github.com/ggQuest/api-v2-nest/pull/155/commits/95f3a4946b4168316ed5336c418ae51631183201

2023-08-31 17:55 UTC, vladikopl01 commented on src/action-registry/action-registry.controller.ts
> +@Controller('action-registry')
Solved in https://github.com/ggQuest/api-v2-nest/pull/155/commits/95f3a4946b4168316ed5336c418ae51631183201

2023-08-31 17:55 UTC, vladikopl01 commented on prisma/schema.prisma
> +  gameId    String   @map("game_id")
Solved in https://github.com/ggQuest/api-v2-nest/pull/155/commits/95f3a4946b4168316ed5336c418ae51631183201

2023-08-31 17:57 UTC, vladikopl01 commented on package-lock.json
Solved in https://github.com/ggQuest/api-v2-nest/pull/155/commits/cba9aa1fb67fc8436aac7b4c92e5c1ed131cdffe

2023-08-31 18:13 UTC, vladikopl01 commented on src/action-registry/action-registry.service.ts
> +  isAllowed(gameId: string, actions: string[]): Promise<boolean> {
Solved in https://github.com/ggQuest/api-v2-nest/pull/155/commits/a4f8d5c16154b9a2219b1d08eea0fbb32234577d

2023-09-01 21:14 UTC, vladikopl01 commented on docker-compose.yml
@yura2100 I suppose we don't have to do it as we rebase the current branch to have #154 changes

2023-09-01 21:21 UTC, vladikopl01 commented
Need to create a migration to merge the PR
I would appreciate it if somebody would do this for me
> Currently, I have problems with my connection and can not access the docker containers

2023-09-04 10:49 UTC, yura2100 requested changes
@vladikopl01 for better code readability I suggest adding `RequestDto` and `ResponseDto` suffixes to all dtos so we could distinguish between them

2023-09-04 10:49 UTC, yura2100 commented on prisma/schema.prisma
> +  hash      String
@vladikopl01 you got the idea of `@@unique` a bit wrong. It creates a composite unique constraint of several fields. For example when you create `@@unique([gameId, action])` that mean that gameId+action are unique. I also propose to add another one unique index for `hash` field separately for DB consistency and faster queries for get one and update methods. See [this](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#unique) for `@unique` API reference

2023-09-04 10:49 UTC, yura2100 commented on src/action-registry/action-registry.controller.spec.ts
> +    }).compile();
Instead of providing a real implementation of service use `mock` function from `jest-mock-extended`. This will allow you to run unit tests without having a dependency from database connection.

Something like this:

```suggestion
    const moduleRef = await Test.createTestingModule({
      controllers: [ActionRegistryController],
      providers: [
        {
          provide: ActionRegistryService,
          useValue: mock<ActionRegistryService>(),
        },
      ],
    }).compile();
```

And you could type `service` as `MockProxy<ActionRegistryService>` so you could use mock functions instead of spies:
```ts
service.getManyByGameId.mockResolvedValue(result);
```

You could also do some stubs testing like:
```ts
expect(service.getManyByGameId).toHaveBeenCalledWith(arg1, arg2, ...);
```

2023-09-04 10:49 UTC, yura2100 commented on src/action-registry/action-registry.controller.ts
> +    @Query(new ValidationPipe({ transform: true }))
I prefer having `new ValidationPipe({ transform: true })` configured globally. However this may break backwards compatibility. Could you please at least have this pipe on controller level?

cc @naelob @developerfred

2023-09-04 10:49 UTC, yura2100 commented on src/action-registry/action-registry.service.spec.ts
> +describe('ActionRegistryService', () => {
Please see comments at `src/action-registry/action-registry.controller.spec.ts`

2023-09-04 10:49 UTC, yura2100 commented on src/action-registry/action-registry.service.spec.ts
> +  // could be removed with strictNullCheck: true, but it may break other services
Having `strictNullCheck` on may increase type safety of whole application. I also prefer having `"strict": true` and `"noUncheckedIndexedAccess": true` for even better reliability. But yes, as @vladikopl01 mentioned, this may break other services

2023-09-04 10:49 UTC, yura2100 commented on src/action-registry/dto/action.dto.ts
> +  @IsUUID()
Why `@IsUUID()` but `id` typed as number?

2023-09-04 10:49 UTC, yura2100 commented on src/action-registry/dto/action.dto.ts
> +  @IsUUID()
Why `@IsUUID()` but `id` typed as number?

2023-09-04 10:49 UTC, yura2100 commented on src/action-registry/dto/actions-page-options.dto.ts
> +export class ActionsPageOptionsDto {
I think this could be a generic dto and we should place it somewhere in `shared` dir. And domain specific dtos could just extend from it

2023-09-04 11:45 UTC, vladikopl01 commented on src/action-registry/action-registry.controller.ts
> +    @Query(new ValidationPipe({ transform: true }))
Solved in https://github.com/ggQuest/api-v2-nest/pull/155/commits/3f823ee72decdb5afdf23bf329ca95691bc82552

2023-09-04 11:48 UTC, vladikopl01 commented on src/action-registry/dto/action.dto.ts
> +  @IsUUID()
Solved in https://github.com/ggQuest/api-v2-nest/pull/155/commits/94c6aa408ba3727ca67ef6858e4ac3a4af2d2d38

2023-09-04 11:48 UTC, vladikopl01 commented on src/action-registry/dto/action.dto.ts
> +  @IsUUID()
Solved in https://github.com/ggQuest/api-v2-nest/pull/155/commits/94c6aa408ba3727ca67ef6858e4ac3a4af2d2d38

2023-09-04 12:03 UTC, vladikopl01 commented on src/action-registry/dto/actions-page-options.dto.ts
> +export class ActionsPageOptionsDto {
@yura2100 Did you mean to leave the `ActionsPageOptionsDto`, and create a shared one as `PageOptionsDto` and extend from it for the actions dto, so will use `ActionsPageOptionsDto` anyways? Or we should just use `PageOptionsDto` as we do not add any properties to it?

2023-09-04 12:13 UTC, vladikopl01 commented on src/action-registry/dto/actions-page-options.dto.ts
> +export class ActionsPageOptionsDto {
Solved in https://github.com/ggQuest/api-v2-nest/pull/155/commits/0f13530c531dc50469c0f63e4ac59fc9c6821516

2023-09-04 12:14 UTC, vladikopl01 commented on prisma/schema.prisma
> +  hash      String
Solved in https://github.com/ggQuest/api-v2-nest/pull/155/commits/254f6d2dcb99c0a1d3f24d071903bb7cbcb15f71

2023-09-04 12:42 UTC, Buidlor approved these changes
ok

2023-09-04 13:23 UTC, vladikopl01 commented on src/action-registry/action-registry.service.spec.ts
> +describe('ActionRegistryService', () => {
Solved in https://github.com/ggQuest/api-v2-nest/pull/155/commits/c25239310136080a0798c78878ea354e132c1d31

2023-09-04 13:23 UTC, vladikopl01 commented on src/action-registry/action-registry.controller.spec.ts
> +    }).compile();
Solved in https://github.com/ggQuest/api-v2-nest/pull/155/commits/c25239310136080a0798c78878ea354e132c1d31

2023-09-04 14:18 UTC, yura2100 requested changes

2023-09-04 14:18 UTC, yura2100 commented on prisma/schema.prisma
> +model Action {
Please also add `ownerId` and reference to corresponding table.
During create you should check that current user is also an owner of a game. For read, update, delete operations this check could be skipped for perf optimization.

2023-09-04 14:18 UTC, yura2100 commented on src/action-registry/action-registry.controller.ts
> +export class ActionRegistryController {
Please add a DELETE method as well

2023-09-04 14:18 UTC, yura2100 commented on src/action-registry/action-registry.controller.ts
> +@UseGuards(AuthGuard)
Please create or use something like `@User()` decorator to extract current user from jwt/session token

https://docs.nestjs.com/custom-decorators#param-decorators

2023-09-04 14:18 UTC, yura2100 commented on src/action-registry/action-registry.service.ts
> +        where: { gameId, ...searchOptionsDto },
Please use full-text search only by human readable action name

2023-09-04 14:18 UTC, yura2100 commented on src/action-registry/action-registry.service.ts
> +      return await this.prismaService.action.findMany({
Please add ordering in alphabetic order

2023-09-04 19:47 UTC, vladikopl01 commented on src/action-registry/action-registry.service.ts
> +      return await this.prismaService.action.findMany({
Solved in https://github.com/ggQuest/api-v2-nest/pull/155/commits/403b69eec7bf92dcecfee79ffb9839dd7af5c32e

2023-09-04 19:47 UTC, vladikopl01 commented on src/action-registry/action-registry.service.ts
> +        where: { gameId, ...searchOptionsDto },
Solved in https://github.com/ggQuest/api-v2-nest/pull/155/commits/403b69eec7bf92dcecfee79ffb9839dd7af5c32e

2023-09-04 20:28 UTC, vladikopl01 commented on src/action-registry/action-registry.controller.ts
> +export class ActionRegistryController {
Solved in https://github.com/ggQuest/api-v2-nest/pull/155/commits/9b1281fe3139857937b198da6a7bd660cf1706e8

2023-09-04 20:54 UTC, vladikopl01 commented on prisma/schema.prisma
> +model Action {
Actually, I think we could add `ownerId` to the `Game` entity. So we will check if the passed `gameId` in the create dto has the corresponding game entity with proper `ownerId`, instead of having `ownerId` right into the `Action` entity.

2023-09-05 09:36 UTC, yura2100 approved these changes

2023-09-05 09:36 UTC, yura2100 commented on prisma/schema.prisma
> +model Action {
@vladikopl01 Yes, this is also an option. However we could also add it to `Action` itself for performance optimization

2023-09-05 10:05 UTC, vladikopl01 commented on prisma/schema.prisma
> +model Action {
@yura2100 I am asking because we do not have any owner state in the `Game` model, so we need to create one or find another approach to not touch existing services. Also, there is no model close to the `User` to get id from. Any ideas on how to solve this?

2023-09-05 10:11 UTC, vladikopl01 commented on prisma/schema.prisma
> +model Action {
@yura2100 I have created a paramDecorator based on the user inside the request but seems we use the default jwt authorization and have user property inside the request as follows: 
```
{"sub":1,"username":"john","iat":...,"exp":...}
```

I think it is better to use a passport and create an appropriate `User` model

2023-09-05 10:24 UTC, vladikopl01 commented on prisma/schema.prisma
> +model Action {
@yura2100 Here is the latest commit with User decorator https://github.com/ggQuest/api-v2-nest/pull/155/commits/592dd32fc801cbb69c915bd43e5cc85cf4d7f316

Perhaps there is some other approach that could suit our needs, but which I have not yet come up with

2023-09-05 12:30 UTC, yura2100 requested changes

2023-09-06 16:40 UTC, vladikopl01 commented on src/action-registry/action-registry.service.ts
Need auth to be estimated

2023-09-06 16:40 UTC, vladikopl01 commented on src/shared/decorators/user.decorator.ts
> +);
Need auth to be estimated

2023-09-06 16:40 UTC, vladikopl01 commented on prisma/schema.prisma
> +model Action {
Need auth to be estimated

2023-09-06 19:41 UTC, merged